apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      securityContext:
        supplementalGroups:
          - 1000
        fsGroup: 1000
      containers:
        - name: hello-kubernetes
          image: paulbouwer/hello-kubernetes:1.10
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "0.5"
            limits:
              memory: "512Mi"
              cpu: "0.5"
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
            allowPrivilegeEscalation: false
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb-ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    #service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:{region}:{user id}:certificate/{id}
    #service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    #external-dns.alpha.kubernetes.io/hostname: hello-kubernetes-nlb.r53domain.com
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
    #- name: https
    #  port: 443
    #  targetPort: 8080
  selector:
    app: hello-kubernetes

